name: Md.Utilities
on:
  push:
    paths:
      - Md.Utilities/**
      - .github/workflows/Md.Utilities.yaml
  workflow_dispatch:
jobs:
  build-and-test:
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-build-and-test.yaml@main
    with:
      solution-directory: Md.Utilities
