name: Md.Utilities
on:
  push:
    paths:
      - Md.Utilities/**
      - .github/workflows/Md.Utilities.yaml
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  create-nuget:
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      project-name: Md.Utilities
      solution-directory: Md.Utilities
  create-code-coverage-page:
    needs: create-nuget
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-code-coverage-page.yaml@main
    with:
      test-project-name: Md.Utilities.Test
      solution-directory: Md.Utilities
