name: Md.Utilities
on:
  push:
    paths:
      - Md.Utilities/**
      - .github/workflows/Md.Utilities.yaml
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  build-and-test:
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      project-name: Md.Utilities
      solution-directory: Md.Utilities
