name: Md.Utilities
on:
  push:
    paths:
      - Md.Utilities/**
      - .github/workflows/Md.Utilities.yaml
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
  packages: write
  pages: write
jobs:
  create-nuget-code-coverage-page:
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-nuget-code-coverage-page.yaml@main
    with:
      project-name: Md.Utilities
      solution-directory: Md.Utilities
      test-project-name: Md.Utilities.Test
